[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.1.0",
    "pocketbase>=0.14.0",
    "serial>=0.0.97",
]

[tool.uv.workspace]
members = ["umbra"]
